server:
  port: 8990 #服务端口号


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-uf6ry261ghx3995253o.mysql.rds.aliyuncs.com:3306/www_finance?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: root

  cloud:
      nacos:
        discovery:
          enabled: false        # 关闭服务注册
          register-enabled: false  # 不向 nacos 注册自己

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.demo.entity
  configuration:
    map-underscore-to-camel-case: true

devtools:
  restart:
    enabled: true  # 开启热部署
    additional-paths: src/main/java # 重启目录
    exclude: WEB-INF/**